### ISSUE TITLE
Uptime aggregation function slow

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big_dipper#1]
The uptime calculation is currently relying on MongoDB aggregation which is very slow when the number of block aggregating is less than the number of blocks we are counting. For example, we are counting the recent 100 blocks for short period uptime, if the blocks signed by a validator is less than 100 blocks, the aggregation will be very slow and make the block data update taking too long time.

Need to find a better way to find the uptime.

**Comment by sherry13131** [comment]
Is the database growing very quickly? Do you think the size of database also affect the performance? (but we need them anyway)
What about not relying on the database but directly pull the block data from chain, but then there will be a lot to do, like implement new helper functions)
Will think about it.

**Comment by kwunyeung** [comment]
It's related to this issue.

https://jira.mongodb.org/browse/SERVER-26337

When the number of records of a validator is less than the $limit, the performance is very slow. For example, if we set the uptime to count the latest 100 blocks. And the validator has just started signing the first block. Our database will have 1 record of this validator and we are trying to aggregate 100 records of this validator. Then the performance will be very slow. How slow? To calculate the uptime of other validators are around 0.1 seconds each but for this new validator, it will take over 30 seconds. So, 300x slower.

**Comment by kwunyeung** [comment]
Currently aggregate every 15 blocks ~ 1.5 mins.

**Comment by kwunyeung** [comment]
Not able to solve in MongoDB level
