### ISSUE TITLE
Rewrite the ledger onclick handlers in ES6

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big_dipper#106]
Rewrite the onclick handlers for the ledger modal in ES6 so that you don't bind every time in the onclick. This will run in every render.

**Comment by ztsai** [comment]
#97

**Comment by ztsai** [comment]
fixed in 5eecb9b7f813ab183d01751fd35819d1adccb72d on ledger feature branch [ledgerFB](https://github.com/forbole/big_dipper/tree/)
