### ISSUE TITLE
Balance is showing null during delegation

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big_dipper#107]
![image](https://user-images.githubusercontent.com/932636/59243074-c73d7500-8c40-11e9-9bca-63578d245a95.png)

There are accounts with and without vesting. We have to cater both types of accounts. And we have to handle this output when the balance is not ready to show.

**Comment by ztsai** [comment]
fixed in 157ccce9aaaa714d065993ab5759c30ffa9613b0 on ledger feature branch [ledgerFB](https://github.com/forbole/big_dipper/tree/ledgerFB)
