### ISSUE TITLE
Show delegations in denom instead of shares

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big_dipper#108]
![image](https://user-images.githubusercontent.com/932636/59243142-171c3c00-8c41-11e9-8d37-8139b2d26198.png)

Most users don't understand the meaning of shares. It's better to show the delegations in denom rather than in shares. This can be calculated by 

![equation](https://latex.codecogs.com/svg.latex?%5Cfn_phv%20delegator%5C%20shares%20%5Ctimes%20validator%5C%20tokens%20%5Cdiv%20valdiator%20%5C%20shares)

**Comment by ztsai** [comment]
#97

**Comment by ztsai** [comment]
on feature branch [ledgerFB](https://github.com/forbole/big_dipper/tree/ledgerFB)
