### ISSUE TITLE
curators should be in a separate service

### ISSUE THREAD

**Issue by ztsai** [forbole/big_dipper#122]
everything in server/main.js should be moved to a standalone service

**Comment by kwunyeung** [comment]
Maybe we can try start it with another process manager and remove the server code from Nginx passenger.

**Comment by ztsai** [comment]
this is causing more and more bugs, therefore mark as P1

**Comment by kwunyeung** [comment]
Build the front and back ends in separate apps and connect them via DDP. Then we can keep all reactivities.

https://stackoverflow.com/questions/44246337/multiple-meteor-apps-with-same-backend

**Comment by kwunyeung** [comment]
close with [curator branch](https://github.com/forbole/big_dipper/tree/curator).
