### ISSUE TITLE
direct link to perform transaction

### ISSUE THREAD

**Issue by ztsai** [forbole/big_dipper#127]
for example, going to `/account/<account_address>/send` will
1. open login modal if user is not logged in or logged in user is not the same as the address returned by ledger 
2. open transfer modal with target address already populated as <account_address>

---
- [x] send: `/account/<account_address>/send`
- [x] delegate: `/validator/<validator_address>/delegate`
- [x] withdraw: `/account/withdraw` (will redirect to /account/<login_user_address> with modal open)

#97

**Comment by ztsai** [comment]
@kwunyeung 
do you think we should have links for redelegation/undelegation? 
I can't think of common use cases for sending someone a link asking them to redelegate/undelegate from a validator, and if it makes sense to have a link for redelegating to a validator

**Comment by kwunyeung** [comment]
Not very useful for redelegation and unbonding, I think.
