### ISSUE TITLE
Sometimes it will show the chain is stopped for over 1 min

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big_dipper#129]
Currently, there is an alert on the home page if the chain stopped over 1 min. It keeps checking the latest state of the chain and therefore, even if BD is not digesting blocks fast enough, as long as the full node has been synced to the latest height, it should report the correct height. I don't see the node BD is monitoring is experiencing any issue. I suspect this is due to missing error handling during Coingecko request.

https://github.com/forbole/big_dipper/blob/b8b9184dc0cc911b7f0306b1fb8d47287665da45/imports/api/coin-stats/server/methods.js#L20

As BD is requesting Coingecko every minute, if the timestamp of the Coingecko record is the same as before, MongoDB will not insert as there is duplicate key. The exception make the process quit and wait for a restart. If it keeps quitting more than one minute, the "stop chain" alert will appear as the chain data hasn't been updated. Please simply do the error handling and see if won't happen.

**Comment by kwunyeung** [comment]
@ztsai I think this should be fixed asap. It happens quite often now.

**Comment by ztsai** [comment]
I think the issue is related to updating `ChainState` rather than `CoinStats`, 

`'E11000 duplicate key error collection: cosmoshub-2.chain_states index: height_-1 dup key: { : 1047183 }'`

the right direction should be fixing #122, but I've created a PR for temporary fixes at #161

**Comment by ztsai** [comment]
@kwunyeung I've deployed the change to prod, let's monitor and see if the issue is fixed
I am gonna keep this issue open until it's confirmed
