### ISSUE TITLE
To show the block heights of the missed blocks of validators

### ISSUE THREAD

**Issue by terencesflam** [forbole/big_dipper#16]
**Is your feature request related to a problem? Please describe.**
Enhance the information about validators

**Describe the solution you'd like**
Show the block heights of the missed blocks of a validator

**Comment by kwunyeung** [comment]
Need to specify what metrics and goals to achieve for show the missed block height.

Some possible metrics for showing missing blocks
1. number of consecutive misses
2. misses in specific time range
3. misses to particular proposers at certain time range
4. missing ratio to certain proposers

Proposer / Voter / Time may review interesting results. The relationship is like how GA provide web traffic between Weekday / Hour.

![image](https://user-images.githubusercontent.com/932636/56887995-90067080-6aa5-11e9-91e0-c94bad29bad2.png)

**Comment by ztsai** [comment]
track in #86
