### ISSUE TITLE
Some validator website links fail

### ISSUE THREAD

**Issue by ebuchman** [forbole/big_dipper#17]
Great work with The Big Dipper!

I believe validators that don't include `https://` in their website URLs are being incorrectly linked to an internal bigdipper.live URL, rather than the intended validator website.

Example: [ATEAM](https://cosmos.bigdipper.live/validator/BAC33F340F3497751F124868F049EC2E8930AC2F) links to https://cosmos.bigdipper.live/validator/nodeateam.com

**Comment by kwunyeung** [comment]
Thanks! Fixed with https://github.com/forbole/big_dipper/commit/69faa7739f11891a2a827018193a441dc81ee517
