### ISSUE TITLE
Display micro-atoms for validators 

### ISSUE THREAD

**Issue by haymond** [forbole/big_dipper#206]
**Is your feature request related to a problem? Please describe.**
Boz from Akash network was looking at our validator list. Instead of looking at voting power, he looked first at "delegator shares" and "tokens" which shows about 457M. He was confused why the validator had more tokens than our total supply. 

**Describe the solution you'd like**
I would like delegator shares and tokens to show "micro-atoms", which are atoms times one million, for the delegator shares and tokens section for validators. 

**Describe alternatives you've considered**
None. It simply needs to be labeled. 

**Additional context**
[Here's the link](https://cosmos.bigdipper.live/validator/2B9A55D3BF93D7375DD207B75C5ED4D2B91D9146) he was looking at.

**Comment by kwunyeung** [comment]
Thanks for the report. In a later version which supports `gaia 2.0.x`, the delegation will be displayed as tokens. Btw, how did you get 457M for total supply?

**Comment by haymond** [comment]
Awesome, that's great to hear. I believe Boz initially looked at delegation shares first and then realized voting power was the ATOM amount later but he was still confused since it's currently not labeled as micro-ATOMs. Glad this will get updated soon.

**Comment by kwunyeung** [comment]
I see. Maybe he mixed up with delegation shares and tokens. Let me ask him and see if he needs help.

**Comment by haymond** [comment]
Oh he mentioned to me on Slack that he figured it out now. Thanks for helping to improve this!
