### ISSUE TITLE
Proposal status not being consistent by incorrectly calculated voting power

### ISSUE THREAD

**Issue by samueltangz** [forbole/big_dipper#215]
**Describe the bug**
The voting power shown on the `/proposals/{id}` endpoint is incorrect. If 

**To Reproduce**
1. Suppose that the voting power is 1000x of the delegated tokens.
2. If we have a passed proposal with id 3, visit `/proposals/3`.
3. The proposal status shows "Passed" while the there is a part in the tally result showing that the proposal is invalid.

**Expected behavior**
The tally result should not show the proposal is invalid.

**Screenshots**

![Screenshot from 2019-11-20 18-03-33](https://user-images.githubusercontent.com/10565444/69229276-1ad4c700-0bc0-11ea-92b9-4c7fd2ff90e0.png)

**Additional context**
The actual voting power should be around 50%, which is 1000x from the wrong value (0.05%)

**Comment by kwunyeung** [comment]
The intepretation of the tally result should only calculate the number of tokens but not voting power as we never know if the project would change the ratio of the token to voting power other than the predefined setup in `Cosmos SDK`.
