### ISSUE TITLE
Why I can not see my validator's info?

### ISSUE THREAD

**Issue by snowdiceX** [forbole/big_dipper#234]
**Describe the bug**
I created a validator success, but I can not see my validator's info in explorer!
Please tell me what should I do.

**To Reproduce**
1. My staking transaction:
Hash
65D2ABADE18444256EFBCCEF198E0C6CD189CD13249DD6A15A2A9158988D5E3C
Height
73,948 17 Dec 2019, 3:57:42pm UTC
Fee
0.001 ATOM
Gas (used / wanted)
116,706 / 116,736

2. My validator status now
./gaiacli status --indent
{
  "node_info": {
    "protocol_version": {
      "p2p": "7",
      "block": "10",
      "app": "0"
    },
    "id": "0572211b0bbdee826ae862a50f94ffc60ea36a8f",
    "listen_addr": "tcp://0.0.0.0:26656",
    "network": "cosmoshub-3",
    "version": "0.32.7",
    "channels": "4020212223303800",
    "moniker": "#Dawns.World",
    "other": {
      "tx_index": "on",
      "rpc_address": "tcp://127.0.0.1:26657"
    }
  },
  "sync_info": {
    "latest_block_hash": "C5F40BD49CD7E6B0FAAE3EC543510B58FB411073B71473AD01175B397194081F",
    "latest_app_hash": "70CFCC26A417F2E4530F66E9F5AABAED96A8B7726AE88D218599CE2F07A8F549",
    "latest_block_height": "85735",
    "latest_block_time": "2019-12-18T14:51:02.936562545Z",
    "catching_up": false
  },
  "validator_info": {
    "address": "2CD6A3523F5D61573EF1E3654B421AD211CFE8DC",
    "pub_key": {
      "type": "tendermint/PubKeyEd25519",
      "value": "rnjPZGsF0MMP/aHilBUaEpimiHb5YBxfNZVGqLOW2ZQ="
    },
    "voting_power": "10"
  }
}

3. validator's account:
https://cosmos.bigdipper.live/account/cosmosvaloper1ktecz4dr56j9tsfh7nwg8s9suvhfu70qykhu5s

Is there something wrong?

**Expected behavior**
How to get my validator's info in the list?

**Comment by kwunyeung** [comment]
Thank you for reporting. I believe this is something related to #204 . Our team is working on resolving this issue. In the meantime, I will pick up your validator address and add it back to the Big Dipper first. It will run automatically afterwards.

**Comment by snowdiceX** [comment]
Thank you all.

**Comment by snowdiceX** [comment]
> Thank you for reporting. I believe this is something related to #204 . Our team is working on resolving this issue. In the meantime, I will pick up your validator address and add it back to the Big Dipper first. It will run automatically afterwards.

Thank you all!

**Comment by kwunyeung** [comment]
@snowdiceX I have fixed some data recorded in the database and it's showing correctly.

https://cosmos.bigdipper.live/validator/cosmosvaloper1ktecz4dr56j9tsfh7nwg8s9suvhfu70qykhu5s

I don't quite get how it wasn't there at the first place as your validator was bonded right after 2 blocks of the `create-validator` transaction and Big Dipper should catch it as it reads the active validators on every block. We will keep an eye on this issue. Thanks!
