### ISSUE TITLE
Wrong number of total validators and delegated tokens

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big_dipper#29]
![image](https://user-images.githubusercontent.com/932636/56466969-9b292300-644b-11e9-82e8-d78707f18df9.png)

The total number of validators and total number of delegated tokens are wrong as the BD get all validators from the LCD and there is a bug https://github.com/cosmos/cosmos-sdk/issues/4099

**Comment by kwunyeung** [comment]
Same as in IRIS

![image](https://user-images.githubusercontent.com/932636/56467229-a2056500-644e-11e9-8299-a7cb833529b3.png)

**Comment by ztsai** [comment]
it's still not correct after upgrading to v0.34.2
The actual count is 124 but home page shows 111 while validator page shows 120(active+inactive)
we only add a validator to database when it becomes or falls out of active validators.  The ones that have been unbonded/unbonding before the fix came out are still not added.
![Screen Shot 2019-05-03 at 10 05 30 AM](https://user-images.githubusercontent.com/1817638/57117014-93db1100-6d8b-11e9-8001-9797546f35f6.png)

![Screen Shot 2019-05-03 at 10 02 29 AM](https://user-images.githubusercontent.com/1817638/57116974-2af39900-6d8b-11e9-8e2f-8b81892f070d.png)
![Screen Shot 2019-05-03 at 10 02 40 AM](https://user-images.githubusercontent.com/1817638/57117018-99385b80-6d8b-11e9-820d-2f54e54288fe.png)
![Screen Shot 2019-05-03 at 10 02 47 AM](https://user-images.githubusercontent.com/1817638/57117019-99d0f200-6d8b-11e9-8e03-e245685ca7b6.png)

**Comment by kwunyeung** [comment]
Should upsert the data to the collection even if they haven't validated any block.

**Comment by kwunyeung** [comment]
Fixed in 637d546ba03bed38979b995b15f99e0098c09631. The total number of validators didn't save before.
