### ISSUE TITLE
Validator voting power remains after unbonding

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big_dipper#4]
If a validator is fully undelegated, the voting power doesn't reset to 0 and status keeps active. Unbonding validators should not be shown as active record miss block.

**Comment by ztsai** [comment]
https://github.com/forbole/big_dipper/commit/d68bc1ccc9930649aa033ea29aadb87c9113419b#diff-cde1506c7965dcf09ab180c8da631843R389
