### ISSUE TITLE
The destination of the link "address" on the section "Delegation"

### ISSUE THREAD

**Issue by terencesflam** [forbole/big_dipper#48]
Currently the link of [each address on the section "delegation"](https://cosmos.bigdipper.live/validator/cosmosvaloper14kn0kk33szpwus9nh8n87fjel8djx0y070ymmj/delegations) of each validator will be directed to "/validator/". As a result, the target destination will show "Validator doesn't exist." if this is not an address of validator.

I think this should be directed to "/account/" instead.

**Comment by kwunyeung** [comment]
fixed by checking out old Account.jsx
