### ISSUE TITLE
Improve the presentation of crypto holdings in "Account Details"

### ISSUE THREAD

**Issue by terencesflam** [forbole/big_dipper#50]
**Is your feature request related to a problem? Please describe.**
The total number of atoms is shown in "k atoms" while the numbers of atoms in "delegation" and "unbonding" sections are shown without units (which are in fact in terms of uatoms). Furthermore the number in Transactions is shown in uatoms.

**Describe the solution you'd like**
1. Showing the total number of atoms in "atoms" would work fine. The theoretical maximum is in 9 digits which is perfectly fine on both desktop and mobile.
2. Showing the numbers in "delegation" and "unbonding" sections in atom as well.
3. Keep using uatom in transactions page, but better find a place to show the proportion "1 atom = 1,000,000 uatom"

**Comment by kwunyeung** [comment]
related to #45
