### ISSUE TITLE
Store validator avatar links instead of querying on render

### ISSUE THREAD

**Issue by ztsai** [forbole/big_dipper#51]
avatar links shouldn't change that often, should probably store it in db and check for updates once in a while instead of checking keybase.io everytime we want to render an avatar

![Screen Shot 2019-05-03 at 10 39 33 AM](https://user-images.githubusercontent.com/1817638/57117590-ec141200-6d8f-11e9-9d2b-6794805c27cf.png)

**Comment by kwunyeung** [comment]
Need a caching time. We don't know when a validator will update their identity, although they should not.

**Comment by kwunyeung** [comment]
It's now storing the database and update again when the validator update the profile.
