### ISSUE TITLE
<Account> sorting doesn't work

### ISSUE THREAD

**Issue by ztsai** [forbole/big_dipper#53]
for example, see voter breakdown for proposals
![Screen Shot 2019-05-03 at 11 03 40 AM](https://user-images.githubusercontent.com/1817638/57118056-321ea500-6d93-11e9-8947-b44aa264767f.png)
![Screen Shot 2019-05-03 at 11 03 52 AM](https://user-images.githubusercontent.com/1817638/57118057-32b73b80-6d93-11e9-93c4-0aa938370efa.png)

this is due to a bug in componentDidUpdate/updateAccount, basically if the new address is not a validator, it will not update 
(also, `this.props != prevProps` doesn't do deep comparison, so updateAccount is actually called more often than needed.)
https://github.com/forbole/big_dipper/commit/588115f1f68503f9f2d99619db4ff88b0bc783bb?w=1#diff-fcf611115cf882d04fab5b927bb37a62L30

**Comment by kwunyeung** [comment]
Tested and deployed.
