### ISSUE TITLE
User Interview

### ISSUE THREAD

**Issue by sirkitree** [forbole/big_dipper#75]
Hi,

I apologize for exploring other avenues if this is the wrong place to talk about this, but I wanted the people involved in this project to know about a project I've been working on to show much of this sort of data and functionality in a spatial computing environment (VR). 

I'm using the data displayed through big_dipper as a sort of guide on what is important to users and it's been a wonderful indicator of that so far!

Seeing as this is a direct corollary project, I thought I might ask if anyone here is interested in a user interview by our designers. This could be written, or we could also meet in VR to do the interview, whatever you prefer.

Our questions are in regards to things like:
- what data you feel is important to know and surface on the dashboard
- how visualizing Cosmos network data might lead to enhanced insights, and what those insights might be
- how you personally use big_dipper to understand the network, and make decisions

If there is someone better suited to asking these sorts of questions about the Cosmos network, and the big_dipper project in general, please let me know.

For further information about our spatial computing project, please take a look at our Paper: [SVC Cosmos VR: Project Overview](https://paper.dropbox.com/doc/SVC-Cosmos-VR-Project-Overview--AdAd3J9zaQ_dy~Phl2Z5NgJHAg-2tvrlIU0NA12XqiXeWIUZ)

**Comment by kwunyeung** [comment]
I have to close this as this is not related to the project itself.
